apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/auth/
patches:
  - path: ./dev-auth-patch-deploy.yaml
  - path: ./dev-auth-patch-service.yaml
images:
  - name: auth-image
    newName: localhost/ardanlabs/auth
    newTag: 0.0.1
